/*
* generated by Xtext
*/
package de.bmw.carit.jnario.spec.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class SpecOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
