/*
* generated by Xtext
*/
package de.bmw.carit.jnario.spec.ui.outline;

import org.eclipse.xtext.xtend2.ui.outline.Xtend2OutlineTreeProvider;

/**
 * Customization of the default outline structure.
 * 
 * @author Jan Koehnlein
 */
public class SpecOutlineTreeProvider extends Xtend2OutlineTreeProvider {


}
