/*
* generated by Xtext
*/
package de.bmw.carit.jnario.spec.ui.labeling;

import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.edit.ui.provider.AdapterFactoryLabelProvider;
import org.eclipse.xtext.naming.SimpleNameProvider;
import org.eclipse.xtext.ui.label.DefaultEObjectLabelProvider;
import org.eclipse.xtext.util.SimpleAttributeResolver;

import com.google.inject.Inject;

/**
 * Provides labels for a EObjects.
 * 
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#labelProvider
 */
public class SpecLabelProvider extends DefaultEObjectLabelProvider {

	@Inject
	public SpecLabelProvider(AdapterFactoryLabelProvider delegate) {
		super(delegate);
	}
	
	String text(EObject ele){
		return ele.eClass().getName() + " " + SimpleAttributeResolver.NAME_RESOLVER.apply(ele);
	}

/*
	//Labels and icons can be computed like this:
	
	String text(MyModel ele) {
	  return "my "+ele.getName();
	}
	 
    String image(MyModel ele) {
      return "MyModel.gif";
    }
*/
}
