/*******************************************************************************
 * Copyright (c) 2012 BMW Car IT and others.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *******************************************************************************/
package org.jnario.jnario.tests.unit.doc

import org.jnario.doc.HtmlFile

describe HtmlFile {

		
	fact "ddd"{
		subject.content = "My Content"
		subject.name = "MyFile.html"
		subject.rootFolder = "../"
		subject.title  = "My Title"
		subject.toText.toString => '''
				<!DOCTYPE html>
				<html lang="en">
				<head>
				<meta charset="utf-8">
				<title>My Title</title>
				<meta name="description" content="">
				<meta name="author" content="Jnario">
				
				<!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
				<!--[if lt IE 9]>
				      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
				    <![endif]-->
				
				<!-- Le styles -->
				<link rel="stylesheet" href="../css/bootstrap.min.css">
				<link rel="stylesheet" href="../css/bootstrap-responsive.min.css">
				<link rel="stylesheet" href="../css/custom.css">
				<link rel="stylesheet" href="../css/prettify.css">
				<script type="text/javascript" src="../js/prettify.js"></script>
				<script type="text/javascript" src="../js/lang-jnario.js"></script>
				</head>
				
				<body onload="prettyPrint()">
					<div class="container">
						<div class="content">
							<div class="page-header">
								<h1>My Title</h1>
							</div>
							<div class="row">
								<div class="span12">
				My Content
								</div>
							</div>
						</div> <!-- /content -->
						<footer>
							<p><small>Generated by <a href="http://www.jnario.org">Jnario</a>.</small></p>
						</footer>
				
					</div>
					<!-- /container -->
				
				</body>
				</html>
		'''.toString
	}
	
}