/*
* generated by Xtext
*/
package de.bmw.carit.xspec.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class XSpecAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/bmw/carit/xspec/parser/antlr/internal/InternalXSpec.tokens");
	}
}
