<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="jnario"
    nsURI="http://www.bmw.de/carit/jnario/Jnario" nsPrefix="jnario">
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//Background"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Background">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="#//ExampleTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="#//Step" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" eSuperTypes="../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepExpression" eType="#//StepExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="and" upperBound="-1" eType="#//Step"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Given" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="When" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="Then" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/XAnnotations.ecore#//XAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockExpression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="heading" eType="#//ExampleHeading"
        containment="true" eOpposite="#//ExampleHeading/table"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="rows" upperBound="-1" eType="#//ExampleRow"
        containment="true" eOpposite="#//ExampleRow/table"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleHeading">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendField"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//ExampleTable"
        eOpposite="#//ExampleTable/heading"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleRow">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parts" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="table" eType="#//ExampleTable"
        eOpposite="#//ExampleTable/rows"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="JnarioFile" eSuperTypes="../../org.eclipse.xtext.xtend2/model/Xtend2.ecore#//XtendFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="GivenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepReference" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Step"/>
  </eClassifiers>
</ecore:EPackage>
