/*
 * generated by Xtext
 */
package de.bmw.carit.xspec.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class XSpecExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return de.bmw.carit.xspec.ui.internal.XSpecActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return de.bmw.carit.xspec.ui.internal.XSpecActivator.getInstance().getInjector("de.bmw.carit.xspec.XSpec");
	}
	
}
