<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="feature"
    nsURI="http://www.org/jnario/feature/Feature" nsPrefix="feature">
  <eClassifiers xsi:type="ecore:EClass" name="Feature" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendClass">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="background" eType="#//Background"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Background">
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scenario" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EReference" name="examples" upperBound="-1"
        eType="ecore:EClass ../../org.jnario/model/Jnario.ecore#//ExampleTable" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="members" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="steps" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Step" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="stepExpression" eType="#//StepExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="and" upperBound="-1" eType="ecore:EClass ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Given" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="When" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="Then" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//Step"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="annotations" upperBound="-1"
        eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/XAnnotations.ecore#//XAnnotation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="blockExpression" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XBlockExpression"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureFile" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="GivenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="WhenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="ThenReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="AndReference" eSuperTypes="#//StepReference"/>
  <eClassifiers xsi:type="ecore:EClass" name="StepReference" eSuperTypes="#//Step">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reference" eType="#//Step"/>
  </eClassifiers>
</ecore:EPackage>
