/*
* generated by Xtext
*/
package de.bmw.carit.jnario.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import de.bmw.carit.jnario.services.JnarioGrammarAccess;

public class JnarioParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private JnarioGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected de.bmw.carit.jnario.parser.antlr.internal.InternalJnarioParser createParser(XtextTokenStream stream) {
		return new de.bmw.carit.jnario.parser.antlr.internal.InternalJnarioParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "JnarioFile";
	}
	
	public JnarioGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(JnarioGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
