/*
* generated by Xtext
*/
package de.bmw.carit.xspec.ui.contentassist;

import de.bmw.carit.xspec.ui.contentassist.AbstractXSpecProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class XSpecProposalProvider extends AbstractXSpecProposalProvider {

}
