/*
* generated by Xtext
*/
package de.bmw.carit.jnario.ui.contentassist;

import de.bmw.carit.jnario.ui.contentassist.AbstractJnarioProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class JnarioProposalProvider extends AbstractJnarioProposalProvider {

}
