<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="spec" nsURI="http://www.org/jnario/spec/Spec" nsPrefix="spec">
  <eClassifiers xsi:type="ecore:EClass" name="SpecFile" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendFile"/>
  <eClassifiers xsi:type="ecore:EClass" name="ExampleGroup" eSuperTypes="../../org.jnario/model/Jnario.ecore#//Specification ../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendMember">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preamble" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetType" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmTypeReference"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetOperation" eType="ecore:EClass ../../org.eclipse.xtext.common.types/model/JavaVMTypes.ecore#//JvmOperation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Example" eSuperTypes="#//TestFunction ../../org.jnario/model/Jnario.ecore#//Executable">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expr" eType="ecore:EClass ../../org.eclipse.xtext.xbase/model/Xbase.ecore#//XExpression"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pending" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Before" eSuperTypes="#//TestFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="After" eSuperTypes="#//TestFunction"/>
  <eClassifiers xsi:type="ecore:EClass" name="TestFunction" eSuperTypes="../../org.eclipse.xtend.core/model/Xtend.ecore#//XtendFunction"/>
</ecore:EPackage>
