/*
* generated by Xtext
*/
package de.bmw.carit.jnario.spec.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class SpecAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/bmw/carit/jnario/spec/parser/antlr/internal/InternalSpec.tokens");
	}
}
