package selenium;

import selenium.SearchingViaGoogleFeatureBackground;

@SuppressWarnings("all")
public class SearchingViaGoogleFeatureSearchingForJnario extends SearchingViaGoogleFeatureBackground {
  public void _whenISearchForJnario() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nname cannot be resolved"
      + "\nsendKeys cannot be resolved"
      + "\nfirst cannot be resolved"
      + "\n+ cannot be resolved"
      + "\nname cannot be resolved"
      + "\nclick cannot be resolved");
  }
  
  public void _thenTheResultShouldContainJnarioExecutableSpecificationsForJava() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Jnario\n"
      + "\nThe method waitUntil is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method findElement is undefined for the type Scenario: Searching for Xtend\n"
      + "\nThe method or field By is undefined for the type Scenario: Searching for Xtend\n"
      + "\nid cannot be resolved"
      + "\n!= cannot be resolved"
      + "\ntagName cannot be resolved"
      + "\ngetText cannot be resolved"
      + "\nshouldcontain cannot be resolved"
      + "\nfirst cannot be resolved");
  }
}
